---
docker_default_settings:
  network: "docker-network-main"
  puid: "{{ system_user_uid }}"
  pgid: "{{ system_user_gid }}"
  tz: "{{ system_timezone }}"

docker_backup_containers:
  - name: "homarr"
    volumes:
      - "/data"
      - "/app/data/configs"

  - name: "immich-db"
    volumes:
      - "/var/lib/postgresql/data"

  - name: "jellyfin"
    volumes:
      - "/config"

  - name: "jellyseerr"
    volumes:
      - "/app/config"

  - name: "prowlarr"
    volumes:
      - "/config"

  - name: "radarr"
    volumes:
      - "/config"

  - name: "sonarr"
    volumes:
      - "/config"

  - name: "transmission"
    volumes:
      - "/config"

  - name: "filebrowser"
    volumes:
      - "/database.db"

  - name: "vaultwarden"
    volumes:
      - "/data"

  - name: "home-assistant"
    volumes:
      - "/config"

  - name: "zigbee2mqtt"
    volumes:
      - "/app/data"
